name: '🐞 Bug Report'
description: Reporta un error en la API backend
labels: ['bug', 'backend', 'api', 'type: bug', 'status: backlog', 'priority: planning']
body:
  - type: markdown
    attributes:
      value: |
        Reporta el bug de forma rápida. ¡Solo lo esencial!

  - type: dropdown
    id: bug-category
    attributes:
      label: Tipo de bug
      options:
        - API Endpoint
        - Database/TypeORM
        - Authentication/JWT
        - Middleware
        - Config/Environment
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: ¿Qué está fallando?
      description: Describe el error brevemente
      placeholder: |
        POST /api/users retorna 500 cuando el email ya existe
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: ¿Cómo reproducirlo?
      description: Pasos para reproducir el error
      placeholder: |
        1. POST /api/users con email duplicado
        2. Retorna 500 en lugar de 400
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ¿Qué esperabas?
      description: Comportamiento esperado
      placeholder: |
        Debería retornar 400 Bad Request con mensaje de error
    validations:
      required: true

  - type: textarea
    id: logs-and-context
    attributes:
      label: Logs, error o contexto adicional (opcional)
      description: Stack trace, logs, endpoint details, etc.
      placeholder: |
        ```
        TypeError: Cannot read property 'id' of undefined
            at UserController.create (/src/controllers/UserController.ts:45:12)
        ```

        Endpoint: POST /api/users
        Env: development, Node 20.x
    validations:
      required: false
