blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Alebat-Education/verticals-next-generations-node-back/blob/main/README.md
    about: Check the project documentation for setup and usage instructions
  - name: 💬 Discussions
    url: https://github.com/Alebat-Education/verticals-next-generations-node-back/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🆘 Critical Security Issues
    url: https://github.com/Alebat-Education/verticals-next-generations-node-back/security/advisories/new
    about: Report critical security vulnerabilities privately
