name: '🚀 Feature Request'
description: Sugiere una nueva funcionalidad o mejora
labels: ['enhancement', 'backend', 'api', 'type: feature', 'status: backlog', 'priority: planning']
body:
  - type: markdown
    attributes:
      value: |
        Describe brevemente qué funcionalidad necesitas. ¡Simple y rápido!

  - type: dropdown
    id: feature-category
    attributes:
      label: Tipo de funcionalidad
      options:
        - New API Endpoint
        - Database/Migration
        - Authentication
        - Middleware
        - Performance
        - Config/Environment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: ¿Qué funcionalidad necesitas?
      description: Describe brevemente lo que quieres implementar
      placeholder: |
        Ejemplo: Endpoint GET /api/users con paginación y filtros
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detalles técnicos (opcional)
      description: Si tienes ideas de implementación, endpoint, queries, etc.
      placeholder: |
        - Request: GET /api/users?page=1&limit=10
        - Response: { users: [...], total: 100 }
        - Requiere índice en users.created_at
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: |
        ¿Has considerado otras formas de implementar esta funcionalidad?
    validations:
      required: false
