name: '🔒 Bug - Security'
description: Vulnerabilidad o problema de seguridad (CONFIDENCIAL)
labels: ['security', 'vulnerability', 'urgent', 'type: bug', 'status: backlog', 'priority: planning']
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Reporte de Seguridad
        **IMPORTANTE:** Si es crítico, considera reportarlo de forma privada primero.
        No incluyas información sensible (passwords, tokens, etc.)

  - type: dropdown
    id: security-category
    attributes:
      label: Tipo de vulnerabilidad
      options:
        - Authentication/Authorization
        - SQL Injection
        - XSS/CSRF
        - Information Disclosure
        - Input Validation
        - JWT Issues
        - CORS/Rate Limiting
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: ¿Qué vulnerabilidad encontraste?
      description: Describe el problema SIN información sensible
      placeholder: |
        El endpoint /api/users permite acceso sin autenticación,
        exponiendo emails de usuarios.
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: ¿Qué está afectado?
      description: Endpoints, archivos o componentes afectados
      placeholder: |
        - GET /api/users
        - /src/middleware/auth.ts
    validations:
      required: true

  - type: textarea
    id: impact-and-steps
    attributes:
      label: Impacto y reproducción (opcional)
      description: Qué podría pasar y cómo reproducirlo de forma segura
      placeholder: |
        Impacto: Acceso no autorizado a datos de usuarios

        Reproducir:
        1. Request a GET /api/users sin token
        2. La API devuelve datos sin verificar permisos
    validations:
      required: false

  - type: textarea
    id: code-snippet
    attributes:
      label: Código relevante (si aplica)
      description: |
        Fragmento de código donde se identifica el problema
      placeholder: |
        ```typescript
        // En userController.ts - falta verificación de autenticación
        async getUsers(req: Request, res: Response) {
          const users = await User.find(); // ❌ Sin verificar permisos
          res.json(users); // ❌ Expone todos los datos
        }
        ```
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: Solución sugerida
      description: |
        Si tienes ideas sobre cómo corregir el problema
      placeholder: |
        1. Agregar middleware de autenticación al endpoint
        2. Implementar verificación de roles/permisos
        3. Filtrar campos sensibles en la respuesta
        4. Agregar rate limiting para prevenir abuso
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: Referencias o recursos
      description: |
        Enlaces a documentación, CVEs, o recursos relacionados
      placeholder: |
        - OWASP Top 10: https://owasp.org/www-project-top-ten/
        - JWT Best Practices: https://tools.ietf.org/html/rfc8725
        - Related CVE: CVE-2024-XXXXX
    validations:
      required: false

  - type: checkboxes
    id: security-checklist
    attributes:
      label: Checklist de seguridad
      description: Confirma que has seguido las mejores prácticas de reporte
      options:
        - label: He verificado que esto es realmente un problema de seguridad
          required: true
        - label: No he incluido credenciales reales o información sensible
          required: true
        - label: He considerado el impacto antes de hacer público este reporte
          required: true
        - label: He probado en un entorno de desarrollo, no en producción
          required: false
